#!/usr/bin/env node

/**
 * Custom Skill Creator
 * Turns workflow descriptions into OpenClaw skills
 */

import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

/**
 * Parse workflow description
 */
function parseWorkflow(description) {
  const lines = description.split('\n').filter(l => l.trim());
  
  const skill = {
    name: '',
    version: '1.0.0',
    description: '',
    trigger: null,
    steps: [],
    tools: []
  };
  
  // Extract name from first line
  if (lines.length > 0) {
    skill.name = lines[0].toLowerCase().replace(/\s+/g, '-');
  }
  
  // Extract description
  if (lines.length > 1) {
    skill.description = lines.slice(1).join(' ');
  }
  
  // Detect trigger
  const triggerPatterns = [
    { pattern: /every (\d+) (hour|day|minute)/i, type: 'schedule' },
    { pattern: /at (\d{1,2}:\d{2})/i, type: 'time' },
    { pattern: /when (.*)/i, type: 'event' }
  ];
  
  for (const tp of triggerPatterns) {
    const match = description.match(tp.pattern);
    if (match) {
      skill.trigger = {
        type: tp.type,
        value: match[0]
      };
      break;
    }
  }
  
  // Detect tools
  const toolPatterns = [
    { pattern: /fetch|get|retrieve/gi, tool: 'web_fetch' },
    { pattern: /search/gi, tool: 'web_search' },
    { pattern: /send|notify|post/gi, tool: 'message' },
    { pattern: /read|write|file/gi, tool: 'fs' },
    { pattern: /execute|run|shell/gi, tool: 'exec' }
  ];
  
  const foundTools = new Set();
  for (const tp of toolPatterns) {
    if (description.match(tp.pattern)) {
      foundTools.add(tp.tool);
    }
  }
  skill.tools = Array.from(foundTools);
  
  // Create steps
  if (skill.tools.length > 0) {
    skill.steps = skill.tools.map(tool => ({
      name: tool,
      tool: tool,
      params: {}
    }));
  }
  
  return skill;
}

/**
 * Generate SKILL.md
 */
function generateSkillMd(skill) {
  let md = `# ${skill.name}\n\n`;
  md += `**Version:** ${skill.version}\n\n`;
  md += `${skill.description}\n\n`;
  md += `## Trigger\n\n`;
  if (skill.trigger) {
    md += `- **Type:** ${skill.trigger.type}\n`;
    md += `- **Value:** ${skill.trigger.value}\n\n`;
  } else {
    md += `- Manual trigger\n\n`;
  }
  
  md += `## Tools Used\n\n`;
  skill.tools.forEach(t => {
    md += `- \`${t}\`\n`;
  });
  md += '\n';
  
  md += `## Steps\n\n`;
  skill.steps.forEach((step, i) => {
    md += `${i + 1}. **${step.name}**\n`;
    md += `   - Tool: \`${step.tool}\`\n`;
    md += `   - Params: ${JSON.stringify(step.params)}\n\n`;
  });
  
  md += `## Usage\n\n`;
  md += '```bash\n';
  md += `# This skill runs on: ${skill.trigger?.value || 'manual trigger'}\n`;
  md += '```\n';
  
  return md;
}

/**
 * Generate skill.js
 */
function generateSkillJs(skill) {
  let js = `// ${skill.name}.js\n`;
  js += `// Generated by Custom Skill Creator\n\n`;
  js += `export const skill = {\n`;
  js += `  name: "${skill.name}",\n`;
  js += `  version: "${skill.version}",\n`;
  js += `  trigger: ${JSON.stringify(skill.trigger, null, 2)},\n`;
  js += `  tools: ${JSON.stringify(skill.tools)},\n`;
  js += `  \n`;
  js += `  async run(context) {\n`;
  
  skill.steps.forEach(step => {
    js += `    // ${step.name}\n`;
    js += `    // await context.${step.tool}(...)\n`;
  });
  
  js += `  }\n`;
  js += `};\n`;
  
  return js;
}

/**
 * Main
 */
function main() {
  const args = process.argv.slice(2);
  const input = args[0];
  
  if (!input) {
    console.log(`
CUSTOM SKILL CREATOR

Usage: node skill-creator.mjs <description-file> [output-dir]

Example:
  echo "daily-crypto-brief
  Check ETH price, check BTC price, post to Discord" > workflow.txt
  node skill-creator.mjs workflow.txt
`);
    return;
  }
  
  // Read description
  let description;
  if (existsSync(input)) {
    description = readFileSync(input, 'utf-8');
  } else {
    description = input;
  }
  
  console.log('🔧 Creating skill from description...\n');
  
  const skill = parseWorkflow(description);
  
  console.log(`Name: ${skill.name}`);
  console.log(`Description: ${skill.description}`);
  console.log(`Trigger: ${skill.trigger?.value || 'manual'}`);
  console.log(`Tools: ${skill.tools.join(', ')}`);
  
  // Create output directory
  const outputDir = args[1] || path.join(__dirname, '..', skill.name);
  if (!existsSync(outputDir)) {
    mkdirSync(outputDir, { recursive: true });
  }
  
  // Write files
  const skillMd = generateSkillMd(skill);
  const skillJs = generateSkillJs(skill);
  
  writeFileSync(path.join(outputDir, 'SKILL.md'), skillMd);
  writeFileSync(path.join(outputDir, 'index.js'), skillJs);
  
  console.log(`\n✅ Skill created!`);
  console.log(`📁 ${outputDir}/`);
  console.log(`   - SKILL.md`);
  console.log(`   - index.js`);
}

main();
