// daily-crypto-brief.js
// Generated by Custom Skill Creator

export const skill = {
  name: "daily-crypto-brief",
  version: "1.0.0",
  trigger: null,
  tools: ["message"],
  
  async run(context) {
    // message
    // await context.message(...)
  }
};
