#!/usr/bin/env node

/**
 * Executive Brief Generator
 * Creates daily agenda from calendar and priorities
 */

import { readFileSync, existsSync } from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

/**
 * Simple priority analyzer
 */
function analyzePriorities(tasks) {
  const high = tasks.filter(t => t.priority === 'high');
  const medium = tasks.filter(t => t.priority === 'medium');
  const low = tasks.filter(t => t.priority === 'low');
  
  return { high, medium, low };
}

/**
 * Generate daily brief
 */
function generateBrief(config) {
  const today = new Date().toISOString().split('T')[0];
  
  console.log('═══════════════════════════════════════');
  console.log('      EXECUTIVE BRIEF');
  console.log(`Date: ${today}`);
  console.log('═══════════════════════════════════════\n');
  
  // Simulated schedule (in real version, would connect to Google Calendar, Apple Calendar)
  const schedule = config.schedule || [
    { time: '09:00', event: 'Team Standup', priority: 'medium' },
    { time: '11:00', event: 'Deep Work Block', priority: 'high' },
    { time: '14:00', event: 'Client Call', priority: 'high' },
    { time: '16:00', event: '1:1 with Team', priority: 'medium' }
  ];
  
  console.log('📅 TODAY\'S SCHEDULE');
  console.log('─'.repeat(40));
  schedule.forEach(item => {
    const icon = item.priority === 'high' ? '🔴' : item.priority === 'medium' ? '🟡' : '🟢';
    console.log(`${item.time} ${icon} ${item.event}`);
  });
  console.log('');
  
  // Tasks
  const tasks = config.tasks || [
    { task: 'Complete research report', priority: 'high' },
    { task: 'Review PRs', priority: 'medium' },
    { task: 'Update documentation', priority: 'low' }
  ];
  
  const prioritized = analyzePriorities(tasks);
  
  console.log('🎯 PRIORITIES');
  console.log('─'.repeat(40));
  
  if (prioritized.high.length > 0) {
    console.log('\n🔴 HIGH PRIORITY:');
    prioritized.high.forEach(t => console.log(`   • ${t.task}`));
  }
  
  if (prioritized.medium.length > 0) {
    console.log('\n🟡 MEDIUM PRIORITY:');
    prioritized.medium.forEach(t => console.log(`   • ${t.task}`));
  }
  
  if (prioritized.low.length > 0) {
    console.log('\n🟢 LOW PRIORITY:');
    prioritized.low.forEach(t => console.log(`   • ${t.task}`));
  }
  
  console.log('\n💡 RECOMMENDATIONS');
  console.log('─'.repeat(40));
  console.log('• Block 2h for deep work at 11:00');
  console.log('• Prepare for client call by 13:30');
  console.log('• Review PRs during low-energy period');
  
  console.log('\n═══════════════════════════════════════');
  console.log('Generated by Roger AI 🦞');
}

// Load config or use defaults
const configPath = path.join(__dirname, 'config.json');
const config = existsSync(configPath) 
  ? JSON.parse(readFileSync(configPath, 'utf-8'))
  : { schedule: null, tasks: null };

generateBrief(config);
