#!/usr/bin/env node

/**
 * Deep Financial Research Report
 * Generates crypto/stock research reports
 */

import https from 'https';
import http from 'http';

// CoinGecko API (free tier)
const COINGECKO_API = 'api.coingecko.com/api/v3';

/**
 * Fetch from API
 */
function fetchApi(url) {
  return new Promise((resolve, reject) => {
    const client = url.startsWith('https') ? https : http;
    const req = client.get(url, {
      headers: {
        'User-Agent': 'Roger-AI-Agent/1.0'
      }
    }, (res) => {
      let data = '';
      res.on('data', chunk => data += chunk);
      res.on('end', () => {
        try {
          resolve(JSON.parse(data));
        } catch (e) {
          resolve({ error: 'Parse error', raw: data.slice(0, 200) });
        }
      });
    }).on('error', reject);
  });
}

/**
 * Get market data
 */
async function getMarketData(coins) {
  const ids = coins.join(',');
  const data = await fetchApi(`https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&ids=${ids}&order=market_cap_desc&sparkline=false&price_change_percentage=24h`);
  return data;
}

/**
 * Generate report
 */
async function generateReport(coinIds = ['ethereum', 'bitcoin']) {
  console.log(`\n📊 Generating research report for ${coinIds.join(', ')}...\n`);
  
  const marketData = await getMarketData(coinIds);
  
  if (!Array.isArray(marketData)) {
    console.log('❌ Error fetching data');
    console.log(marketData);
    return;
  }
  
  console.log('═══════════════════════════════════════');
  console.log('   FINANCIAL RESEARCH REPORT');
  console.log('═══════════════════════════════════════\n');
  
  // For each coin
  for (const coin of marketData) {
    console.log(`📊 ${coin.name.toUpperCase()} (${coin.symbol.toUpperCase()})`);
    console.log('─'.repeat(40));
    console.log(`Price:      $${coin.current_price?.toLocaleString() || 'N/A'}`);
    console.log(`24h Change: ${coin.price_change_percentage_24h?.toFixed(2) || 'N/A'}%`);
    console.log(`Market Cap: $${(coin.market_cap / 1e9)?.toFixed(1) || 'N/A'}B`);
    console.log(`Volume:     $${(coin.total_volume / 1e9)?.toFixed(1) || 'N/A'}B`);
    console.log(`Rank:       #${coin.market_cap_rank || 'N/A'}`);
    console.log('');
    
    // Analysis
    const change = coin.price_change_percentage_24h || 0;
    if (change > 5) {
      console.log('📈 Strong upward momentum (+5%+)');
    } else if (change > 0) {
      console.log('📊 Slight positive');
    } else if (change > -5) {
      console.log('📉 Minor pullback');
    } else {
      console.log('🔻 Significant drop');
    }
    console.log('');
  }
  
  console.log('═══════════════════════════════════════');
  console.log('Generated by Roger AI Research Agent 🦞');
}

// Parse arguments
const args = process.argv.slice(2);
const coins = args.length > 0 ? args : ['ethereum', 'bitcoin'];

generateReport(coins).catch(console.error);
