#!/usr/bin/env node

/**
 * Expert Voice-Coder
 * Turns plain-English product ideas into working apps
 */

import readline from 'readline';
import { fileURLToPath } from 'url';
import path from 'path';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// Simple CLI interface
const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});

const QUESTION = `
=== Expert Voice-Coder ===

Describe your product idea in plain English.
Example: "Build me a crypto portfolio tracker that shows my ETH and USDC balances, alerts me when prices change by 5%, and lets me set take-profit levels."

Type your idea (or 'quit' to exit):
> `;

function askQuestion(prompt) {
  return new Promise((resolve) => {
    rl.question(prompt, resolve);
  });
}

async function generateProject(idea) {
  console.log('\n🎯 Analyzing your idea...\n');
  
  // Extract key requirements from the idea
  const ideaLower = idea.toLowerCase();
  
  // Detect features
  const features = [];
  if (ideaLower.includes('price') || ideaLower.includes('balance')) {
    features.push('price tracking');
  }
  if (ideaLower.includes('alert') || ideaLower.includes('notify')) {
    features.push('alerts');
  }
  if (ideaLower.includes('portfolio')) {
    features.push('portfolio management');
  }
  if (ideaLower.includes('chart') || ideaLower.includes('graph')) {
    features.push('charts');
  }
  if (ideaLower.includes('buy') || ideaLower.includes('sell') || ideaLower.includes('trade')) {
    features.push('trading');
  }
  
  // Detect tech stack
  let techStack = 'Node.js';
  if (ideaLower.includes('solidity') || ideaLower.includes('smart contract')) {
    techStack = 'Solidity + Hardhat';
  } else if (ideaLower.includes('react') || ideaLower.includes('frontend')) {
    techStack = 'React + Node.js';
  } else if (ideaLower.includes('python')) {
    techStack = 'Python';
  }
  
  // Generate SPEC.md
  const spec = `# ${idea}

## Generated by Expert Voice-Coder
Date: ${new Date().toISOString().split('T')[0]}

## Description
${idea}

## Features
${features.map(f => `- ${f}`).join('\n')}

## Tech Stack
- ${techStack}

## Project Structure
\`\`\`
project/
├── SPEC.md           # This file
├── README.md         # How to run
├── src/
│   └── index.${techStack === 'Python' ? 'py' : 'js'}
└── package.json     # Dependencies
\`\`\`

## Implementation

### Step 1: Setup
\`\`\`bash
mkdir my-project
cd my-project
npm init -y
\`\`\`

### Step 2: Main Code
\`\`\`javascript
// src/index.js - Core implementation
console.log('Project: ${idea.replace(/'/g, "\\'")}');
console.log('Features:', ${JSON.stringify(features)});
\`\`\`

## Status
Ready to implement
`;
  
  // Create project directory with timestamp
  const timestamp = Date.now();
  const projectName = `project-${timestamp}`;
  const projectPath = path.join(__dirname, '..', projectName);
  
  const fs = await import('fs');
  fs.mkdirSync(projectPath, { recursive: true });
  fs.mkdirSync(path.join(projectPath, 'src'), { recursive: true });
  
  // Write SPEC.md
  fs.writeFileSync(path.join(projectPath, 'SPEC.md'), spec);
  
  // Write README.md
  const readme = `# ${projectName}

## Setup
\`\`\`bash
cd ${projectName}
npm install
node src/index.js
\`\`\`

## Idea
${idea}
`;
  fs.writeFileSync(path.join(projectPath, 'README.md'), readme);
  
  // Write main code
  const mainCode = `// ${projectName}
// Generated by Expert Voice-Coder
// Date: ${new Date().toISOString()}

console.log('🎯 ${projectName}');
console.log('Features:', ${JSON.stringify(features)});
console.log('Tech Stack:', '${techStack}');
console.log('\\n✅ Project generated successfully!');
`;
  
  fs.writeFileSync(path.join(projectPath, 'src', `index.${techStack === 'Python' ? 'py' : 'js'}`), mainCode);
  
  // Write package.json
  const packageJson = {
    name: projectName,
    version: '1.0.0',
    type: 'module',
    scripts: {
      start: 'node src/index.js'
    }
  };
  fs.writeFileSync(path.join(projectPath, 'package.json'), JSON.stringify(packageJson, null, 2));
  
  console.log('\n✅ Project generated!');
  console.log(`📁 Location: ${projectPath}`);
  console.log('\nNext steps:');
  console.log(`  cd ${projectPath}`);
  console.log('  npm install');
  console.log('  npm start');
  console.log('');
}

// Main loop
async function main() {
  console.clear();
  console.log('═══════════════════════════════════════');
  console.log('      EXPERT VOICE-CODER v1.0         ');
  console.log('═══════════════════════════════════════');
  
  while (true) {
    const idea = await askQuestion(QUESTION);
    
    if (idea.toLowerCase() === 'quit' || idea.toLowerCase() === 'exit') {
      console.log('👋 Goodbye!');
      rl.close();
      process.exit(0);
    }
    
    if (idea.trim().length < 10) {
      console.log('❌ Please describe your idea in more detail.\n');
      continue;
    }
    
    await generateProject(idea);
    console.log('\n═══════════════════════════════════════');
  }
}

main();
