#!/usr/bin/env bash
set -euo pipefail

# Generate Agent Profiles from crawled data
# Usage: bash scripts/generate-agent-profiles.sh [--output-dir docs/agents]

WORKSPACE="${OPENCLAW_WORKSPACE:-$HOME/.openclaw/workspace}"
DATA_DIR="$WORKSPACE/data"
AGENTS_FILE="$DATA_DIR/agents.json"
OUTPUT_DIR="$WORKSPACE/docs/agents"
INDEX_MD="$OUTPUT_DIR/README.md"

# Ensure output directory exists
mkdir -p "$OUTPUT_DIR"

# Verify agents file exists
if [[ ! -f "$AGENTS_FILE" ]]; then
  echo "Error: Agents file not found: $AGENTS_FILE"
  echo "Run crawl-virtuals-agents.sh first"
  exit 1
fi

# Count agents
COUNT=$(jq 'length' "$AGENTS_FILE")
echo "Generating profiles for $COUNT agents..."

# Generate index page
cat > "$INDEX_MD" << 'HEADER'
# Virtuals Protocol Agent Directory

**Generated:** AUTO_DATE
**Source:** Virtuals Protocol ACP
**Total Agents:** AUTO_COUNT

---

## Browse by Category

- [Analysis](#analysis) - Market intelligence, sentiment tracking
- [Trading](#trading) - DeFi strategies, portfolio management
- [Research](#research) - Ecosystem analysis, onchain execution
- [DeFi](#defi) - Yield optimization, strategy selection
- [Community](#community) - Engagement, meme generation
- [General](#general) - Multi-modal, cross-platform

---

## Agent List

HEADER

# Replace placeholders
sed -i '' "s/AUTO_DATE/$(date -u +%Y-%m-%dT%H:%M:%SZ)/" "$INDEX_MD"
sed -i '' "s/AUTO_COUNT/$COUNT/" "$INDEX_MD"

# Generate profile for each agent
jq -r '.[] | @json' "$AGENTS_FILE" | while read -r agent_json; do
  id=$(echo "$agent_json" | jq -r '.id')
  name=$(echo "$agent_json" | jq -r '.name')
  description=$(echo "$agent_json" | jq -r '.description')
  category=$(echo "$agent_json" | jq -r '.category')
  market_cap=$(echo "$agent_json" | jq -r '.market_cap')
  token=$(echo "$agent_json" | jq -r '.token_symbol')
  capabilities=$(echo "$agent_json" | jq -r '.capabilities | join(", ")')
  wallet=$(echo "$agent_json" | jq -r '.wallet_address')
  twitter=$(echo "$agent_json" | jq -r '.social.twitter // "N/A"')
  launch=$(echo "$agent_json" | jq -r '.launch_date')
  
  # Create profile markdown
  cat > "$OUTPUT_DIR/$id.md" << PROFILE
# $name

**Category:** $category  
**Token:** $token  
**Market Cap:** \$$market_cap  
**Launch:** $launch  
**Twitter:** $twitter  

---

## Description

$description

---

## Capabilities

$capabilities

---

## Onchain Identity

**Wallet:** \`$wallet\`  
**Chain:** Base  

---

## Market Data

| Metric | Value |
|--------|-------|
| Market Cap | \$$market_cap |
| Token Symbol | $token |
| Category | $category |

---

## Social Presence

- **Twitter:** $twitter

---

## Related Agents

<!-- Auto-generated: agents in same category -->

---

*Profile generated by agent-discovery MVP*
PROFILE

  echo "✓ Generated: $OUTPUT_DIR/$id.md"
  
  # Add to index
  echo "- **[$name](./$id.md)** - $description" >> "$INDEX_MD"
done

# Finalize index
cat >> "$INDEX_MD" << 'FOOTER'

---

## About This Directory

This directory is part of the **Agent Discovery MVP** - a proof-of-concept for discovering, comparing, and tracking AI agents on Base.

**Features:**
- Crawl 100+ agents from Virtuals Protocol
- Search by capability/category
- Agent profiles with market data
- Onchain identity tracking

**Next Steps:**
- V1: Onchain registry smart contract
- V1: Reputation system
- V2: Agent-to-agent discovery (x402)
- V2: API for programmatic access

---

*Generated by Roger - Autonomous Research Agent*
FOOTER

echo ""
echo "=== Profile Generation Complete ==="
echo "Total profiles: $COUNT"
echo "Output directory: $OUTPUT_DIR"
echo "Index file: $INDEX_MD"
echo ""
echo "=== Sample Profile ==="
head -20 "$OUTPUT_DIR/aixbt.md"
