#!/usr/bin/env bash
# Refresh deterministic 30-day portfolio state.

set -euo pipefail

WORKSPACE="${OPENCLAW_WORKSPACE:-$HOME/.openclaw/workspace}"
LEDGER="$WORKSPACE/state/project-ledger.json"
QUEUE="$WORKSPACE/state/base-opportunity-queue.json"
REPORT="$WORKSPACE/state/runtime/portfolio-tribunal-$(date -u +%Y%m%d-%H%M%S).md"
MODE="--refresh"

usage() {
  cat <<USAGE
Usage:
  $0 --validate
  $0
  $0 --agent-help
USAGE
}

agent_help() {
  cat <<HELP
portfolio-tribunal refreshes or validates Roger's fixed 30-day portfolio.

Validation checks:
- exactly one ACTIVE_PRIMARY
- exactly one ACTIVE_RESERVE
- exactly two MAINTAIN_PROOF wedges

Refresh mode rewrites base-opportunity-queue.json to match the tribunal decision.
HELP
}

case "${1:-}" in
  --validate)
    MODE="--validate"
    ;;
  -h|--help)
    usage
    exit 0
    ;;
  --agent-help)
    agent_help
    exit 0
    ;;
esac

if [[ "$MODE" == "--validate" ]]; then
  jq -e '
    .primary_id == "agent_security_scanner"
    and .reserve_id == "base_account_miniapp_probe"
    and ([.projects[] | select(.status == "ACTIVE_PRIMARY")] | length) == 1
    and ([.projects[] | select(.status == "ACTIVE_RESERVE")] | length) == 1
    and ([.projects[] | select(.status == "MAINTAIN_PROOF")] | length) == 2
  ' "$LEDGER" >/dev/null
  echo "PORTFOLIO_TRIBUNAL_VALIDATE_OK $LEDGER"
  exit 0
fi

WORKSPACE_ENV="$WORKSPACE" python3 - <<'PY'
import json, os, pathlib
from datetime import datetime, timezone

ws = pathlib.Path(os.environ["WORKSPACE_ENV"])
now = datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")
ledger = json.loads((ws/'state/project-ledger.json').read_text())
queue_path = ws/'state/base-opportunity-queue.json'
queue = json.loads(queue_path.read_text())
status_map = {p['id']: p['status'] for p in ledger['projects']}
proof_map = {
    'agent_security_scanner': {
        'stage': 'PROOF_SPEC',
        'research_packet_path': 'docs/wedges/agent_security_scanner/research-packet.md',
        'proof_spec_path': 'docs/wedges/agent_security_scanner/proof-spec.md',
        'public_proof_url': None,
        'distribution_status': 'not_started',
        'last_stage_advance_at': now,
        'last_artifact_change_at': now,
        'kill_criteria_hit': False,
        'switch_review_required': False,
        'next_action': {
            'type': 'build_primary_wedge',
            'command': 'cd ~/.openclaw/workspace && bash scripts/agent-security-scanner.sh --sample --output docs/wedges/agent_security_scanner/sample-audit.md',
            'target': 'docs/wedges/agent_security_scanner/sample-audit.md',
            'proof_expected': 'sample security audit generated by the canonical scanner script'
        },
        'status': 'active'
    },
    'base_account_miniapp_probe': {
        'stage': 'RESEARCH_PACKET',
        'research_packet_path': 'docs/wedges/base_account_miniapp_probe/research-packet.md',
        'proof_spec_path': 'docs/wedges/base_account_miniapp_probe/proof-spec.md',
        'public_proof_url': None,
        'distribution_status': 'not_started',
        'last_stage_advance_at': now,
        'last_artifact_change_at': None,
        'kill_criteria_hit': False,
        'switch_review_required': True,
        'status': 'queued'
    },
    'base_gas_tracker_v2': {
        'stage': 'MAINTAIN',
        'research_packet_path': None,
        'proof_spec_path': None,
        'public_proof_url': 'https://roger-base.github.io/base-gas-tracker/',
        'distribution_status': 'proof_anchor_live',
        'last_stage_advance_at': now,
        'last_artifact_change_at': '2026-03-07T23:34:16Z',
        'kill_criteria_hit': False,
        'switch_review_required': False,
        'status': 'maintain'
    },
    'contextkeeper_mvp': {
        'stage': 'MAINTAIN',
        'research_packet_path': None,
        'proof_spec_path': None,
        'public_proof_url': None,
        'distribution_status': 'internal_first',
        'last_stage_advance_at': now,
        'last_artifact_change_at': '2026-03-07T19:35:00Z',
        'kill_criteria_hit': False,
        'switch_review_required': False,
        'status': 'maintain'
    },
    'x402_paid_api_demo': {
        'stage': 'FROZEN',
        'research_packet_path': None,
        'proof_spec_path': None,
        'public_proof_url': None,
        'distribution_status': 'frozen',
        'last_stage_advance_at': now,
        'last_artifact_change_at': None,
        'kill_criteria_hit': False,
        'switch_review_required': True,
        'status': 'frozen'
    },
    'erc8004_registry_utility': {
        'stage': 'FROZEN',
        'research_packet_path': None,
        'proof_spec_path': None,
        'public_proof_url': None,
        'distribution_status': 'frozen',
        'last_stage_advance_at': now,
        'last_artifact_change_at': None,
        'kill_criteria_hit': False,
        'switch_review_required': True,
        'status': 'frozen'
    },
    'bankr_operator_console': {
        'stage': 'FROZEN',
        'research_packet_path': None,
        'proof_spec_path': None,
        'public_proof_url': None,
        'distribution_status': 'frozen',
        'last_stage_advance_at': now,
        'last_artifact_change_at': None,
        'kill_criteria_hit': False,
        'switch_review_required': True,
        'status': 'frozen'
    }
}
for op in queue['opportunities']:
    pid = op['id']
    if pid in status_map:
        op['portfolio_status'] = status_map[pid]
    if pid in proof_map:
        op.update(proof_map[pid])
queue['updated_at'] = now
queue['selected_opportunity'] = 'agent_security_scanner'
queue['portfolio_strategy'] = 'one_primary_one_reserve'
queue['active_wedge'] = 'agent_security_scanner'
queue['reserve_wedge'] = 'base_account_miniapp_probe'
queue['maintenance_wedges'] = ['base_gas_tracker_v2', 'contextkeeper_mvp']
queue['frozen_reference_projects'] = [
    'x402_paid_api_demo', 'erc8004_registry_utility', 'bankr_operator_console',
    'base-beginner-guide', 'base-portfolio', 'base-send', 'base-receive',
    'base_gas_tracker_static_duplicate', 'base_gas_tracker_builder_duplicate'
]
queue_path.write_text(json.dumps(queue, indent=2) + '\n')
PY

{
  echo "# Portfolio Tribunal Refresh"
  echo
  echo "- timestamp: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo "- ledger: state/project-ledger.json"
  echo "- queue: state/base-opportunity-queue.json"
  echo
  echo "## Result"
  echo "- primary: agent_security_scanner"
  echo "- reserve: base_account_miniapp_probe"
  echo "- maintain: base_gas_tracker_v2, contextkeeper_mvp"
  echo "- frozen: x402_paid_api_demo, erc8004_registry_utility, bankr_operator_console, generic/reference projects"
} > "$REPORT"

echo "PORTFOLIO_TRIBUNAL_REFRESH_OK $REPORT"
