#!/bin/bash
# Walter Autonomous Research Trigger
# Executes research tasks when Roger is idle
# Part of Walter's autonomous research system

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
STATE_DIR="/Users/roger/.openclaw/workspace/state"
WALTER_DIR="/Users/roger/.openclaw/workspace/walter"
OUTPUT_DIR="/Users/roger/.openclaw/workspace/output"
MONITOR="$SCRIPT_DIR/walter-coordination-monitor.sh"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m'

get_timestamp() {
    date -u +"%Y-%m-%dT%H:%M:%SZ"
}

get_date_stamp() {
    date +"%Y%m%d"
}

log() {
    echo -e "${CYAN}[$(date +%H:%M:%S)]${NC} $1"
}

# Ensure output directory exists
init() {
    mkdir -p "$OUTPUT_DIR/research"
    mkdir -p "$OUTPUT_DIR/logs"
    log "Initialized autonomous research system"
}

# Check if we should run autonomous research
check_prerequisites() {
    # Check if Roger is idle
    local idle_status=$($MONITOR status 2>/dev/null)
    local idle_state=$(echo "$idle_status" | cut -d: -f1)
    
    if [[ "$idle_state" != "idle" ]]; then
        log "${YELLOW}Roger is active. Skipping autonomous research.${NC}"
        return 1
    fi

    # Check if there are queued tasks
    local next_task=$($MONITOR next-task 2>/dev/null)
    if [[ "$next_task" == "No tasks queued" || -z "$next_task" ]]; then
        log "${YELLOW}No research tasks queued.${NC}"
        return 1
    fi

    log "${GREEN}Roger is idle. Starting autonomous research...${NC}"
    return 0
}

# Execute research task using the framework
execute_protocol_analysis() {
    local task_id="$1"
    local description="$2"
    local target="$3"
    local output_file="$OUTPUT_DIR/research/protocol-analysis-$(get_date_stamp)-$(echo $task_id | cut -d- -f2).md"

    log "Starting protocol analysis: $description"
    
    # Create research output based on framework
    cat > "$output_file" << EOF
# Protocol Analysis: $description

**Task ID:** $task_id  
**Executed:** $(get_timestamp)  
**Autonomous:** Yes  
**Roger Status:** Idle  

## Framework Applied: Protocol Analysis Pattern

---

## 1. RECON (Orientation)

**Research Question:** $description  
**Target:** $target  

**Scope:** Deep research following Walter's R-A-D-S cycle

---

## 2. ANALYSIS (Deep Dive)

### Core Protocol Structure
- [ ] Identify the protocol's core abstraction layers
- [ ] Map dependencies and integration points
- [ ] Find load-bearing components

### Trust Assumptions
- [ ] Document trust assumptions explicitly
- [ ] Identify centralization risks
- [ ] Assess upgrade mechanisms

### Security Considerations
- [ ] Check for security audits
- [ ] Review incident reports
- [ ] Identify known vulnerabilities

### Real Usage
- [ ] Find actual usage data (not marketing)
- [ ] Identify key integrations
- [ ] Assess adoption trends

---

## 3. DISTILLATION (Extraction)

### One-Sentence Summary
\[To be completed with core insight\]

### Key Architectural Decisions
1. \[Decision 1\]
2. \[Decision 2\]
3. \[Decision 3\]

### Critical Dependencies
- \[Dependency 1\]
- \[Dependency 2\]

### Failure Modes
- \[Failure mode 1\]
- \[Failure mode 2\]

---

## 4. SYNTHESIS (Output)

### Verdict (STEER Framework)

**S - State conclusion first:**
\[Clear verdict: use / avoid / research more / not applicable\]

**T - Test threshold:**
\[When this applies\]

**E - Explicit confidence:**
\[High/Medium/Low confidence with evidence\]

**E - Evidence:**
\[Specific examples\]

**R - Rebuttal check:**
\[Strongest counter-argument and response\]

---

## Integration Points

### For Roger:
- \[How this connects to Roger's current work\]
- \[Specific recommendations\]

### Risk Assessment:
- \[High/Medium/Low\]
- \[Key risks\]

---

## Next Steps

1. \[Action item 1\]
2. \[Action item 2\]
3. \[Action item 3\]

---

*Generated by Walter Autonomous Research System*  
*Research Framework: /Users/roger/.openclaw/workspace/walter/research-framework.md*
EOF

    log "${GREEN}✓ Created research template: $output_file${NC}"
    echo "$output_file"
}

execute_ecosystem_mapping() {
    local task_id="$1"
    local description="$2"
    local target="$3"
    local output_file="$OUTPUT_DIR/research/ecosystem-map-$(get_date_stamp)-$(echo $task_id | cut -d- -f2).md"

    log "Starting ecosystem mapping: $description"
    
    cat > "$output_file" << EOF
# Ecosystem Mapping: $description

**Task ID:** $task_id  
**Executed:** $(get_timestamp)  
**Autonomous:** Yes  
**Roger Status:** Idle  

## Framework Applied: Ecosystem Mapping Pattern

---

## 1. Key Players

| Project/Protocol | Role | Maturity | Notes |
|------------------|------|----------|-------|
| \[Player 1\] | \[Role\] | \[Maturity\] | \[Notes\] |
| \[Player 2\] | \[Role\] | \[Maturity\] | \[Notes\] |
| \[Player 3\] | \[Role\] | \[Maturity\] | \[Notes\] |

---

## 2. Relationship Graph

\[Text-based diagram or description\]

```
[Central Protocol/Standard]
    ├── [Project A] - [role]
    ├── [Project B] - [role]
    └── [Project C] - [role]
```

---

## 3. Gravity Wells

What everything connects to:
- \[Gravity well 1\] - Why it matters
- \[Gravity well 2\] - Why it matters

---

## 4. Standards & Interfaces

Common patterns:
- \[Standard 1\]
- \[Standard 2\]

---

## 5. Emerging vs Legacy

**Emerging Patterns:**
- \[Pattern 1\]
- \[Pattern 2\]

**Legacy Approaches:**
- \[Approach 1\]
- \[Approach 2\]

---

## 6. Entry Points

Where to start:
1. \[Entry point 1\]
2. \[Entry point 2\]

---

## 7. Strategic Positioning

### Where Walter/Roger Fit:
- \[Positioning analysis\]

### Key Relationships to Build:
- \[Relationship 1\]
- \[Relationship 2\]

---

## Synthesis

### Verdict
\[Clear recommendation for Roger\]

### Priority Actions
1. \[Action 1\]
2. \[Action 2\]

---

*Generated by Walter Autonomous Research System*  
*Research Framework: /Users/roger/.openclaw/workspace/walter/research-framework.md*
EOF

    log "${GREEN}✓ Created ecosystem map: $output_file${NC}"
    echo "$output_file"
}

execute_gap_analysis() {
    local task_id="$1"
    local description="$2"
    local target="$3"
    local output_file="$OUTPUT_DIR/research/gap-analysis-$(get_date_stamp)-$(echo $task_id | cut -d- -f2).md"

    log "Starting gap analysis: $description"
    
    cat > "$output_file" << EOF
# Gap Analysis: $description

**Task ID:** $task_id  
**Executed:** $(get_timestamp)  
**Autonomous:** Yes  
**Roger Status:** Idle  

## Framework Applied: Gap Analysis Pattern

---

## 1. Problem Definition

\[Precise definition of the problem space\]

---

## 2. Existing Solutions Inventory

### Solution A:
- **Name:** \[Name\]
- **Why it falls short:** \[Specific reason\]
- **Evidence:** \[Links/refs\]

### Solution B:
- **Name:** \[Name\]
- **Why it falls short:** \[Specific reason\]
- **Evidence:** \[Links/refs\]

### Solution C:
- **Name:** \[Name\]
- **Why it falls short:** \[Specific reason\]
- **Evidence:** \[Links/refs\]

---

## 3. Gap Verification

### Is this gap real?
- \[ ] Searched workspace for existing solutions
- \[ ] Searched web for similar projects
- \[ ] Checked if gap is solved problem I'm unaware of
- \[ ] Verified gap is worth filling

### Who would use this?
\[Specific users, not "the ecosystem"\]

---

## 4. Build Assessment

### Can we build it well?
- \[Honest assessment\]

### Is this highest-value use of time?
- \[Comparison with other opportunities\]

---

## Verdict (STEER)

**S - State conclusion:**
\[Build / Don't build / Research more\]

**T - Test threshold:**
\[When this applies\]

**E - Explicit confidence:**
\[Confidence level + evidence\]

**E - Evidence:**
\[Specific examples\]

**R - Rebuttal:**
\[Counter-argument and response\]

---

## Recommendation for Roger

\[Clear next step\]

---

*Generated by Walter Autonomous Research System*  
*Research Framework: /Users/roger/.openclaw/workspace/walter/research-framework.md*
EOF

    log "${GREEN}✓ Created gap analysis: $output_file${NC}"
    echo "$output_file"
}

# Main execution flow
run_autonomous_research() {
    init

    if ! check_prerequisites; then
        exit 0
    fi

    # Get next task
    local task_json=$($MONITOR next-task 2>/dev/null | jq -r . 2>/dev/null || echo "")
    if [[ -z "$task_json" || "$task_json" == "null" || "$task_json" == "No tasks queued" ]]; then
        log "${YELLOW}No valid tasks found${NC}"
        exit 0
    fi

    local task_id=$(echo "$task_json" | jq -r '.id')
    local task_type=$(echo "$task_json" | jq -r '.type')
    local task_desc=$(echo "$task_json" | jq -r '.description')
    local task_target=$(echo "$task_json" | jq -r '.target // ""')

    log "${BLUE}Starting task: $task_id${NC}"
    log "${BLUE}Type: $task_type${NC}"
    log "${BLUE}Description: $task_desc${NC}"

    # Mark task as started
    $MONITOR start-task "$task_id" 2>/dev/null

    # Execute based on type
    local output_file=""
    case "$task_type" in
        protocol_analysis)
            output_file=$(execute_protocol_analysis "$task_id" "$task_desc" "$task_target")
            ;;
        ecosystem_mapping)
            output_file=$(execute_ecosystem_mapping "$task_id" "$task_desc" "$task_target")
            ;;
        gap_analysis)
            output_file=$(execute_gap_analysis "$task_id" "$task_desc" "$task_target")
            ;;
        *)
            log "${YELLOW}Unknown task type: $task_type${NC}"
            # Generic research output
            output_file="$OUTPUT_DIR/research/generic-$(get_date_stamp)-$(echo $task_id | cut -d- -f2).md"
            cat > "$output_file" << EOF
# Research: $task_desc

**Task ID:** $task_id  
**Type:** $task_type  
**Executed:** $(get_timestamp)  
**Autonomous:** Yes  

## Framework Applied: R-A-D-S Cycle

## Research Output

\[Research to be completed following framework at /Users/roger/.openclaw/workspace/walter/research-framework.md\]

---

*Generated by Walter Autonomous Research System*
EOF
            ;;
    esac

    # Mark task as completed
    $MONITOR complete-task "$task_id" "$output_file" 2>/dev/null

    log "${GREEN}✓ Autonomous research completed${NC}"
    log "${GREEN}  Output: $output_file${NC}"

    # Create handoff summary
    local handoff_file="$STATE_DIR/walter-handoff-research-$(get_date_stamp).json"
    cat > "$handoff_file" << EOF
{
  "timestamp": "$(get_timestamp)",
  "type": "autonomous_research",
  "taskId": "$task_id",
  "taskType": "$task_type",
  "description": "$task_desc",
  "outputFile": "$output_file",
  "executedWhileRogerIdle": true,
  "requiresResponse": false,
  "summary": "Completed $task_type research: $task_desc",
  "forRoger": "Review output file for findings and recommendations"
}
EOF

    log "${CYAN}📋 Created handoff: $handoff_file${NC}"
    log "${GREEN}✓ Ready for Roger review when he returns${NC}"
}

# Show status
show_status() {
    log "Walter Autonomous Research System Status"
    log "========================================"
    
    # Check Roger status
    local idle_status=$($MONITOR status 2>/dev/null)
    log "Roger status: $idle_status"
    
    # Check queue
    local next_task=$($MONITOR next-task 2>/dev/null)
    log "Next task: $next_task"
    
    # List recent outputs
    log ""
    log "Recent research outputs:"
    ls -lt "$OUTPUT_DIR/research/" 2>/dev/null | head -5 || log "No outputs yet"
}

# Command handler
case "${1:-}" in
    run)
        run_autonomous_research
        ;;
    status)
        show_status
        ;;
    help|--help|-h)
        echo "Walter Autonomous Research Trigger"
        echo ""
        echo "Commands:"
        echo "  run      - Execute research if Roger idle and tasks queued"
        echo "  status   - Show system status"
        echo ""
        echo "This script integrates with:"
        echo "  - walter-coordination-monitor.sh (track Roger availability)"
        echo "  - walter/research-framework.md (research methodology)"
        echo ""
        echo "Usage:"
        echo "  Add tasks: ./walter-coordination-monitor.sh add-task \<type\> \<desc\>"
        echo "  Run research: ./walter-autonomous-research.sh run"
        ;;
    *)
        show_status
        ;;
esac
